(Get-Item HKLM:\SOFTWARE\Microsoft\).OpenSubKey('.NETFramework', $true).CreateSubKey('v2.0.50727').SetValue('SchUseStrongCrypto', 1, 'DWord')
(Get-Item HKLM:\SOFTWARE\Wow6432Node\Microsoft\).OpenSubKey('.NETFramework', $true).CreateSubKey('v2.0.50727').SetValue('SchUseStrongCrypto', 1, 'DWord')

(Get-Item HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\).OpenSubKey('Ciphers', $true).CreateSubKey('RC4 40/128').SetValue('Enabled', 0, 'DWord')
(Get-Item HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\).OpenSubKey('Ciphers', $true).CreateSubKey('RC4 56/128').SetValue('Enabled', 0, 'DWord')
(Get-Item HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\).OpenSubKey('Ciphers', $true).CreateSubKey('RC4 128/128').SetValue('Enabled', 0, 'DWord')
(Get-Item HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\).OpenSubKey('Ciphers', $true).CreateSubKey('Triple DES 168').SetValue('Enabled', 0, 'DWord')

(Get-Item HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\).OpenSubKey('Protocols', $true).CreateSubKey('SSL 2.0').CreateSubKey('Client').SetValue('DisabledByDefault', 1, 'DWord')
(Get-Item HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\).OpenSubKey('Protocols', $true).CreateSubKey('SSL 2.0').CreateSubKey('Client').SetValue('Enabled', 0, 'DWord')
(Get-Item HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\).OpenSubKey('Protocols', $true).CreateSubKey('SSL 2.0').CreateSubKey('Server').SetValue('DisabledByDefault', 1, 'DWord')
(Get-Item HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\).OpenSubKey('Protocols', $true).CreateSubKey('SSL 2.0').CreateSubKey('Server').SetValue('Enabled', 0, 'DWord')

(Get-Item HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\).OpenSubKey('Protocols', $true).CreateSubKey('SSL 3.0').CreateSubKey('Client').SetValue('DisabledByDefault', 1, 'DWord')
(Get-Item HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\).OpenSubKey('Protocols', $true).CreateSubKey('SSL 3.0').CreateSubKey('Client').SetValue('Enabled', 0, 'DWord')
(Get-Item HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\).OpenSubKey('Protocols', $true).CreateSubKey('SSL 3.0').CreateSubKey('Server').SetValue('DisabledByDefault', 1, 'DWord')
(Get-Item HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\).OpenSubKey('Protocols', $true).CreateSubKey('SSL 3.0').CreateSubKey('Server').SetValue('Enabled', 0, 'DWord')

(Get-Item HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\).OpenSubKey('Protocols', $true).CreateSubKey('TLS 1.0').CreateSubKey('Client').SetValue('DisabledByDefault', 1, 'DWord')
(Get-Item HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\).OpenSubKey('Protocols', $true).CreateSubKey('TLS 1.0').CreateSubKey('Client').SetValue('Enabled', 0, 'DWord')
(Get-Item HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\).OpenSubKey('Protocols', $true).CreateSubKey('TLS 1.0').CreateSubKey('Server').SetValue('DisabledByDefault', 1, 'DWord')
(Get-Item HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\).OpenSubKey('Protocols', $true).CreateSubKey('TLS 1.0').CreateSubKey('Server').SetValue('Enabled', 0, 'DWord')

(Get-Item HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\).OpenSubKey('Protocols', $true).CreateSubKey('TLS 1.1').CreateSubKey('Client').SetValue('DisabledByDefault', 1, 'DWord')
(Get-Item HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\).OpenSubKey('Protocols', $true).CreateSubKey('TLS 1.1').CreateSubKey('Client').SetValue('Enabled', 0, 'DWord')
(Get-Item HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\).OpenSubKey('Protocols', $true).CreateSubKey('TLS 1.1').CreateSubKey('Server').SetValue('DisabledByDefault', 1, 'DWord')
(Get-Item HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\).OpenSubKey('Protocols', $true).CreateSubKey('TLS 1.1').CreateSubKey('Server').SetValue('Enabled', 0, 'DWord')

(Get-Item HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\).OpenSubKey('Protocols', $true).CreateSubKey('TLS 1.2').CreateSubKey('Client').SetValue('DisabledByDefault', 0, 'DWord')
(Get-Item HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\).OpenSubKey('Protocols', $true).CreateSubKey('TLS 1.2').CreateSubKey('Client').SetValue('Enabled', 1, 'DWord')
(Get-Item HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\).OpenSubKey('Protocols', $true).CreateSubKey('TLS 1.2').CreateSubKey('Server').SetValue('DisabledByDefault', 0, 'DWord')
(Get-Item HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\).OpenSubKey('Protocols', $true).CreateSubKey('TLS 1.2').CreateSubKey('Server').SetValue('Enabled', 1, 'DWord')
(Get-Item HKLM:\SOFTWARE\Microsoft\).OpenSubKey('.NETFramework', $true).CreateSubKey('v2.0.50727').SetValue('SchUseStrongCrypto', 1, 'DWord')
(Get-Item HKLM:\SOFTWARE\Wow6432Node\Microsoft\).OpenSubKey('.NETFramework', $true).CreateSubKey('v2.0.50727').SetValue('SchUseStrongCrypto', 1, 'DWord')

(Get-Item HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\).OpenSubKey('Ciphers', $true).CreateSubKey('RC4 40/128').SetValue('Enabled', 0, 'DWord')
(Get-Item HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\).OpenSubKey('Ciphers', $true).CreateSubKey('RC4 56/128').SetValue('Enabled', 0, 'DWord')
(Get-Item HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\).OpenSubKey('Ciphers', $true).CreateSubKey('RC4 128/128').SetValue('Enabled', 0, 'DWord')
(Get-Item HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\).OpenSubKey('Ciphers', $true).CreateSubKey('Triple DES 168').SetValue('Enabled', 0, 'DWord')

(Get-Item HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\).OpenSubKey('Protocols', $true).CreateSubKey('TLS 1.2').CreateSubKey('Client').SetValue('DisabledByDefault', 0, 'DWord')
(Get-Item HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\).OpenSubKey('Protocols', $true).CreateSubKey('TLS 1.2').CreateSubKey('Client').SetValue('Enabled', 1, 'DWord')
(Get-Item HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\).OpenSubKey('Protocols', $true).CreateSubKey('TLS 1.2').CreateSubKey('Server').SetValue('DisabledByDefault', 0, 'DWord')
(Get-Item HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\).OpenSubKey('Protocols', $true).CreateSubKey('TLS 1.2').CreateSubKey('Server').SetValue('Enabled', 1, 'DWord')

(Get-Item HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\).OpenSubKey('Protocols', $true).CreateSubKey('TLS 1.3').CreateSubKey('Client').SetValue('DisabledByDefault', 0, 'DWord')
(Get-Item HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\).OpenSubKey('Protocols', $true).CreateSubKey('TLS 1.3').CreateSubKey('Client').SetValue('Enabled', 1, 'DWord')
(Get-Item HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\).OpenSubKey('Protocols', $true).CreateSubKey('TLS 1.3').CreateSubKey('Server').SetValue('DisabledByDefault', 0, 'DWord')
(Get-Item HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\).OpenSubKey('Protocols', $true).CreateSubKey('TLS 1.3').CreateSubKey('Server').SetValue('Enabled', 1, 'DWord')



---
- name: Configure Windows Registry Entries
  hosts: windows_target
  tasks:

  - name: Enable .NETFramework Strong Crypto
    win_regedit:
      path: "HKLM:\SOFTWARE\{{ item.path }}\Microsoft\.NETFramework\v2.0.50727"
      name: SchUseStrongCrypto
      data: 1
      datatype: dword
    with_items:
      - { path: '' }
      - { path: 'Wow6432Node' }

  - name: Disable Weak Ciphers
    win_regedit:
      path: "HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\{{ item.cipher }}"
      name: Enabled
      data: 0
      datatype: dword
    with_items:
      - { cipher: 'RC4 40/128' }
      - { cipher: 'RC4 56/128' }
      - { cipher: 'RC4 128/128' }
      - { cipher: 'Triple DES 168' }

  - name: Configure SCHANNEL Protocols
    win_regedit:
      path: "HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\{{ item.protocol }}\{{ item.type }}"
      name: "{{ item.name }}"
      data: "{{ item.data }}"
      datatype: dword
    with_items:
      - { protocol: 'SSL 2.0', type: 'Client', name: 'DisabledByDefault', data: 1 }
      - { protocol: 'SSL 2.0', type: 'Client', name: 'Enabled', data: 0 }
      # ... Add similar entries for other protocols and types ...

  - name: Enable TLS 1.2 and 1.3
    win_regedit:
      path: "HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\{{ item.protocol }}\{{ item.type }}"
      name: "{{ item.name }}"
      data: "{{ item.data }}"
      datatype: dword
    with_items:
      - { protocol: 'TLS 1.2', type: 'Client', name: 'DisabledByDefault', data: 0 }
      - { protocol: 'TLS 1.2', type: 'Client', name: 'Enabled', data: 1 }
      - { protocol: 'TLS 1.2', type: 'Server', name: 'DisabledByDefault', data: 0 }
      - { protocol: 'TLS 1.2', type: 'Server', name: 'Enabled', data: 1 }
      - { protocol: 'TLS 1.3', type: 'Client', name: 'DisabledByDefault', data: 0 }
      - { protocol: 'TLS 1.3', type: 'Client', name: 'Enabled', data: 1 }
      - { protocol: 'TLS 1.3', type: 'Server', name: 'DisabledByDefault', data: 0 }
      - { protocol: 'TLS 1.3', type: 'Server', name: 'Enabled', data: 1 }
